site_name: codeftc
theme:
  name: simple-blog
  theme_style: dark
  site_name_style: bold
  title_style: bold
  favicon: /assets/favicon.ico
nav:
  - Home: index.md
  - Navigate:
    - Introduction: intro.md
    - Drivetrains: drivetrain.md
    - Control Theory: control.md
    - Closed Loop Control: closed-loop.md
    - PID Control: pid.md
    - Roadrunner: roadrunner.md
